version: '3.8'

services:
    webserver:
        image: 'nginx:alpine'
        container_name: projeto-nginx
        working_dir: /app
        volumes:
            - './:/app'
            - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '9090:80'

    php-fpm:
        build: .docker/php-fpm
        container_name: projeto-php
        working_dir: /app
        expose:
            - 9000
        volumes:
            - './:/app'